### ISSUE TITLE
Background color config issues

### ISSUE THREAD

**Issue by LiHRaM** [kennylevinsen/wldash#31]
I decided to configure wldash to match my theme, using the following settings:
```yaml
background:
  red: 233.0
  green: 228.0
  blue: 226.0
  opacity: 0.9
```
This seems to really mess with the font rendering.
![image](https://user-images.githubusercontent.com/25297553/83947905-3af56c00-a81a-11ea-9cb7-d0d6603c6914.png)
